import "./globals.css";
import { Inter } from "next/font/google";

import NavigationBar from "@/components/NavigationBar";
import { WagmiConfig, configureChains, createConfig } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { publicClient } = configureChains();

  // const config = createConfig({
  //   publicClient,
  // });

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <WagmiConfig config={}> */}
        <NavigationBar />
        {children}
        {/* </WagmiConfig> */}
      </body>
    </html>
  );
}
