"use client";

import "./globals.css";
import { Inter } from "next/font/google";

import { WagmiConfig, configureChains, createConfig } from "wagmi";
import { sepolia } from "@wagmi/core/chains";
import { alchemyProvider } from "@wagmi/core/providers/alchemy";
import NavigationBar from "@/components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { chains, publicClient } = configureChains(
    [sepolia],
    [alchemyProvider({ apiKey: process.env.ALCHEMY_API_KEY as string })]
  );

  const config = createConfig({
    autoConnect: true,
    publicClient,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={config}>
          <NavigationBar />
          {children}
        </WagmiConfig>
      </body>
    </html>
  );
}
